---
- name: Install MySQL-Python
  yum: name=MySQL-python state=installed
  
- name: Create the keystone database
  mysql_db: name={{ openstack_keystone_dbname }} state=present
  
- name: Grant proper access to the keystone database
  mysql_user: name={{ openstack_keystone_db_user_name }} password={{ openstack_keystone_db_user_pass }} priv={{ openstack_keystone_dbname }}.*:ALL host={{ item }} state=present
  with_items:
  - localhost
  - '%'